#!/usr/bin/env -S deno run -A --no-lock
import { defineMatrix, step, workflow } from "jsr:@david/gagen@0.8.0";

const matrix = defineMatrix({
  os: ["ubuntu-latest", "windows-latest", "macos-latest"],
});
const isLinux = matrix.os.equals("ubuntu-latest");

const checkout = step({
  name: "Checkout",
  uses: "actions/checkout@v7",
});

const installNode = step.dependsOn(checkout)({
  name: "Install Node.js",
  uses: "actions/setup-node@v7",
  with: {
    // node --test with a glob requires node 21+
    "node-version": 22,
    cache: "npm",
  },
});

const installDependencies = step.dependsOn(installNode)({
  name: "Install dependencies",
  run: "npm ci",
});

const typeCheck = step.dependsOn(installDependencies)({
  name: "Type check",
  run: "npx tsc -p . --noEmit",
});

const build = step.dependsOn(installDependencies)({
  name: "Build",
  run: "npm run compile",
});

const unitTests = step.dependsOn(installDependencies)({
  name: "Unit tests",
  run: "npm run test:unit",
});

const checkFormatting = step.dependsOn(checkout).if(isLinux)({
  name: "Check formatting",
  uses: "dprint/check@v2.5",
});

const installDeno = step({
  name: "Install Deno",
  uses: "denoland/setup-deno@v2",
});

const lintCiGeneration = step.dependsOn(checkout, installDeno).if(isLinux)({
  name: "Lint CI generation",
  run: "deno run -A --no-lock .github/workflows/ci.ts --lint",
});

workflow({
  name: "CI",
  on: {
    pull_request: { branches: ["main"] },
    push: { branches: ["main"] },
  },
  jobs: [{
    id: "build",
    name: `build (${matrix.os})`,
    runsOn: matrix.os,
    strategy: {
      matrix,
      failFast: false,
    },
    steps: [typeCheck, build, unitTests, checkFormatting, lintCiGeneration],
  }],
}).writeOrLint({
  filePath: new URL("./ci.generated.yml", import.meta.url),
  header: "# GENERATED BY ./ci.ts -- DO NOT DIRECTLY EDIT",
});
