#!/usr/bin/env -S deno run -A --no-lock
import { defineMatrix, step, workflow } from "jsr:@david/gagen@0.8.0";

const matrix = defineMatrix({
  os: ["ubuntu-latest", "windows-latest", "macos-latest"],
});
const isLinux = matrix.os.equals("ubuntu-latest");

const checkout = step({
  name: "Checkout",
  uses: "actions/checkout@v7",
});

const installNode = step.dependsOn(checkout)({
  name: "Install Node.js",
  uses: "actions/setup-node@v7",
  with: {
    "node-version": 24,
    cache: "npm",
  },
});

const installDependencies = step.dependsOn(installNode)({
  name: "Install dependencies",
  run: "npm ci",
});

const typeCheck = step.dependsOn(installDependencies)({
  name: "Type check",
  run: "npx tsc -p . --noEmit",
});

const build = step.dependsOn(installDependencies)({
  name: "Build",
  run: "npm run compile",
});

const unitTests = step.dependsOn(installDependencies)({
  name: "Unit tests",
  run: "npm run test:unit",
});

// the integration tests run the dprint that's on the path
const installDprint = step({
  name: "Install dprint",
  shell: "bash",
  run: [
    `if [ "$RUNNER_OS" = "Windows" ]; then`,
    `  pwsh -Command "iwr https://dprint.dev/install.ps1 -useb | iex"`,
    `  echo "$USERPROFILE\\\\.dprint\\\\bin" >> "$GITHUB_PATH"`,
    `else`,
    `  curl -fsSL https://dprint.dev/install.sh | sh`,
    `  echo "$HOME/.dprint/bin" >> "$GITHUB_PATH"`,
    `fi`,
  ],
});

const integrationTests = step.dependsOn(installDependencies, installDprint)({
  name: "Integration tests",
  shell: "bash",
  run: [
    // vscode needs a display, which the Linux runner doesn't have
    `if [ "$RUNNER_OS" = "Linux" ]; then`,
    `  xvfb-run -a npm test`,
    `else`,
    `  npm test`,
    `fi`,
  ],
});

const checkFormatting = step.dependsOn(checkout).if(isLinux)({
  name: "Check formatting",
  uses: "dprint/check@v2.5",
});

const installDeno = step({
  name: "Install Deno",
  uses: "denoland/setup-deno@v2",
});

const lintCiGeneration = step.dependsOn(checkout, installDeno).if(isLinux)({
  name: "Lint CI generation",
  run: [
    "deno run -A --no-lock .github/workflows/ci.ts --lint",
    "deno run -A --no-lock .github/workflows/publish.ts --lint",
  ],
});

workflow({
  name: "CI",
  on: {
    pull_request: { branches: ["main"] },
    push: { branches: ["main"] },
  },
  jobs: [{
    id: "build",
    name: `build (${matrix.os})`,
    runsOn: matrix.os,
    strategy: {
      matrix,
      failFast: false,
    },
    steps: [typeCheck, build, unitTests, integrationTests, checkFormatting, lintCiGeneration],
  }],
}).writeOrLint({
  filePath: new URL("./ci.generated.yml", import.meta.url),
  header: "# GENERATED BY ./ci.ts -- DO NOT DIRECTLY EDIT",
});
