#!/usr/bin/env -S deno run -A --no-lock
import { step, workflow } from "jsr:@david/gagen@0.8.0";

const checkout = step({
  name: "Checkout",
  uses: "actions/checkout@v7",
});

const installNode = step.dependsOn(checkout)({
  name: "Install Node.js",
  uses: "actions/setup-node@v7",
  with: {
    "node-version": 24,
    cache: "npm",
  },
});

const installDependencies = step.dependsOn(installNode)({
  name: "Install dependencies",
  run: "npm ci",
});

const verifyVersion = step.dependsOn(installDependencies)({
  name: "Verify tag matches package.json version",
  run: [
    `VERSION=$(node -p "require('./package.json').version")`,
    `if [ "$GITHUB_REF_TYPE" = "tag" ] && [ "$GITHUB_REF_NAME" != "$VERSION" ]; then`,
    `  echo "Tag $GITHUB_REF_NAME does not match the package.json version $VERSION."`,
    `  exit 1`,
    `fi`,
  ],
});

const packageExtension = step.dependsOn(verifyVersion)({
  name: "Package",
  // runs the vscode:prepublish script, which builds the extension
  run: "npx vsce package --out dprint.vsix",
});

const publishMarketplace = step.dependsOn(packageExtension)({
  name: "Publish to the VS Code Marketplace",
  env: { VSCE_PAT: "${{ secrets.VSCE_PAT }}" },
  run: "npx vsce publish --packagePath dprint.vsix",
});

const publishOpenVsx = step.dependsOn(packageExtension)({
  name: "Publish to Open VSX",
  env: { OVSX_PAT: "${{ secrets.OVSX_PAT }}" },
  run: "npx ovsx publish dprint.vsix",
});

workflow({
  name: "publish",
  on: {
    workflow_dispatch: {},
    push: { tags: ["*.*.*"] },
  },
  permissions: { contents: "read" },
  jobs: [{
    id: "publish",
    name: "publish",
    runsOn: "ubuntu-latest",
    timeoutMinutes: 30,
    steps: [publishMarketplace, publishOpenVsx],
  }],
}).writeOrLint({
  filePath: new URL("./publish.generated.yml", import.meta.url),
  header: "# GENERATED BY ./publish.ts -- DO NOT DIRECTLY EDIT",
});
