#!/usr/bin/env -S deno run -A --no-lock
import { artifact, job, step, workflow } from "jsr:@david/gagen@0.8.0";

// the package is built once and each marketplace is published to in a separate
// job so that a failure in one can be re-run without affecting the other
const vsix = artifact("vsix");

const checkout = step({
  name: "Checkout",
  uses: "actions/checkout@v7",
});

const installNode = step.dependsOn(checkout)({
  name: "Install Node.js",
  uses: "actions/setup-node@v7",
  with: {
    "node-version": 24,
    cache: "npm",
  },
});

const installDependencies = step.dependsOn(installNode)({
  name: "Install dependencies",
  run: "npm ci",
});

const verifyVersion = step.dependsOn(installDependencies)({
  name: "Verify tag matches package.json version",
  run: [
    `VERSION=$(node -p "require('./package.json').version")`,
    `if [ "$GITHUB_REF_TYPE" = "tag" ] && [ "$GITHUB_REF_NAME" != "$VERSION" ]; then`,
    `  echo "Tag $GITHUB_REF_NAME does not match the package.json version $VERSION."`,
    `  exit 1`,
    `fi`,
  ],
});

const packageExtension = step.dependsOn(verifyVersion)({
  name: "Package",
  // runs the vscode:prepublish script, which bundles the extension and its
  // dependencies, so node_modules isn't packaged
  run: "npx vsce package --no-dependencies --out dprint.vsix",
});

const packageJob = job("package", {
  runsOn: "ubuntu-latest",
  timeoutMinutes: 15,
  steps: step.dependsOn(packageExtension)(
    vsix.upload({ path: "dprint.vsix", retentionDays: 7 }),
  ),
});

const downloadPackage = step.dependsOn(installDependencies)(
  vsix.download({ dirPath: "." }),
);

// signs in as the Microsoft Entra ID app that's a member of the marketplace publisher,
// which trusts the workflow's OIDC token for the "publish" environment
const azureLogin = step({
  name: "Azure login",
  uses: "azure/login@v3",
  with: {
    "client-id": "${{ vars.AZURE_CLIENT_ID }}",
    "tenant-id": "${{ vars.AZURE_TENANT_ID }}",
    "allow-no-subscriptions": true,
  },
});

const marketplaceJob = job("marketplace", {
  name: "publish to the VS Code Marketplace",
  needs: [packageJob],
  runsOn: "ubuntu-latest",
  environment: "publish",
  permissions: { contents: "read", "id-token": "write" },
  timeoutMinutes: 15,
  steps: step.dependsOn(downloadPackage, azureLogin)({
    name: "Publish",
    run: "npx vsce publish --packagePath dprint.vsix --azure-credential",
  }),
});

const openVsxJob = job("open-vsx", {
  name: "publish to Open VSX",
  needs: [packageJob],
  runsOn: "ubuntu-latest",
  environment: "publish",
  permissions: { contents: "read", "id-token": "write" },
  timeoutMinutes: 15,
  steps: step.dependsOn(downloadPackage)({
    name: "Publish",
    // exchanges the workflow's OIDC token for a short-lived publishing token,
    // which is configured on open-vsx.org for this workflow file
    run: "npx ovsx publish dprint.vsix --trusted-publishing",
  }),
});

workflow({
  name: "publish",
  on: {
    workflow_dispatch: {},
    push: { tags: ["*.*.*"] },
  },
  permissions: { contents: "read" },
  jobs: [packageJob, marketplaceJob, openVsxJob],
}).writeOrLint({
  filePath: new URL("./publish.generated.yml", import.meta.url),
  header: "# GENERATED BY ./publish.ts -- DO NOT DIRECTLY EDIT",
});
